title: Council of Knaves Test
author: Blue Mana Games
email: bluemanagames@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Testing ssite to learn github pages.
# social links
github_username: councilofknaves

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
